name: 'FTP Upload'

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to FTPServer
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./output/
          server-dir: /
          exclude: |
            *.pkl
            *.log
            readme
      - name: Commit and push if changed
        run: |
          rm -f config/mydemo.txt
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          deleted=false
          if [ -f output/tv.txt ]; then
            git rm output/tv.txt
            deleted=true
          fi
          if [ -f output/tv.m3u ]; then
            git rm output/tv.m3u
            deleted=true
          fi
          if [ "$deleted" = true ]; then
            git commit -m "Delete file"
            git push
          else
            echo "No files to delete, skipping commit."
          fi