name: 'FTP Upload'

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to FTPServer
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./output/
          server-dir: /
          exclude: |
            *.pkl
            *.log
      - name: Delete specified files
        run: |
          if [ -f config/mydemo.txt ]; then
            rm -f config/mydemo.txt
            echo "Deleted config/mydemo.txt"
          else
            echo "config/mydemo.txt does not exist"
          fi

          if [ -f output/tv.txt ]; then
            rm -f output/tv.txt
            echo "Deleted output/tv.txt"
          else
            echo "output/tv.txt does not exist"
          fi

          if [ -f output/tv.m3u ]; then
            rm -f output/tv.m3u
            echo "Deleted output/tv.m3u"
          else
            echo "output/tv.m3u does not exist"
          fi