name: 'FTP Upload'

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to FTPServer
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./output/
          server-dir: /
          exclude: |
            *.pkl
            *.log
      - name: Commit and push if changed
        run: |
          rm -f config/mydemo.txt
          rm -f output/tv.txt
          rm -f output/tv.m3u
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git commit -m "Delete file"
          git push